ansible_user                 : daniel_zaharchenk00
#ansible_ssh_private_key_file : /home/daniel_zaharchenk00/.ssh/petProj

jenkins_url                  :
nexus_url                    :
#jenkins_home                 :
#groovy_dir                   : {{ jenkins_home }}/init.groovy.d/
