ansible_user                  : dzakharchenko
ansible_ssh_private_key_file  : /Users/dzakharchenko/.ssh/id_rsa

jenkins_url                  : 35.246.253.248
nexus_url                    :
jenkins_home                 : /var/lib/jenkins
#groovy_dir                   : {{ jenkins_home }}/init.groovy.d/
